gslab_version: 4.1.0

build:
  prepare_data: build/prepare_data
  descriptive: build/descriptive

source:
  prepare_data: source/prepare_data
  descriptive: source/descriptive

input: None

executable_names:
  python: None
  r: None
  stata: None
  matlab: None
  lyx: none
  latex: None

prereq_checks:
  git_lfs: Yes
  gslab_python: Yes
  python: Yes
  r: No
  stata: No
  matlab: No
  lyx: No
  latex: No

scons_debrief_args:
  look_in: release;source            
  file_MB_limit_lfs: 2               
  total_MB_limit_lfs: 500            
  file_MB_limit: 0.5                 
  total_MB_limit: 125                
  git_attrib_path: ../.gitattributes 
  MAXIT: 10                          
  log: state_of_repo.log             